spring:
  datasource:
    url: jdbc:mysql://localhost:3306/six?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username : root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: shop-product-producer
server:
  port: 8092
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: t_
      table-underline: false
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
feign:
  hystrix:
    enabled: true

